apiVersion: apps/v1
kind: Deployment
metadata:
  name: bqstoragereadclient-9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bqstoragereadclient-9
  template:
      metadata:
        labels:
          app: bqstoragereadclient-9
      spec:
        containers:
        - name: bqstoragereadclient-9
          image: gcr.io/level-approach-382012/bq_storage_reader_client_9:latest
