apiVersion: apps/v1
kind: Deployment
metadata:
  name: bqstoragereadclient-7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bqstoragereadclient-7
  template:
      metadata:
        labels:
          app: bqstoragereadclient-7
      spec:
        containers:
        - name: bqstoragereadclient-7
          image: gcr.io/level-approach-382012/bq_storage_reader_client_7:latest
