apiVersion: apps/v1
kind: Deployment
metadata:
  name: bqstoragereadclient-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bqstoragereadclient-8
  template:
      metadata:
        labels:
          app: bqstoragereadclient-8
      spec:
        containers:
        - name: bqstoragereadclient-8
          image: gcr.io/level-approach-382012/bq_storage_reader_client_8:latest
